// Generated by Haxe 4.0.0-preview.4+1e3e5e0
(function () { "use strict";
var $hxEnums = {};
var _$Tmp_Comment_$Impl_$ = {};
_$Tmp_Comment_$Impl_$._new = function(note) {
	var this1 = note;
	return this1;
};
_$Tmp_Comment_$Impl_$.getAuthor = function(this1) {
	return this1.author;
};
var _$Tmp_Post_$Impl_$ = {};
_$Tmp_Post_$Impl_$._new = function(post) {
	var this1 = post;
	return this1;
};
_$Tmp_Post_$Impl_$.getPostText = function(this1) {
	return this1.text;
};
var Comment2 = function(author,text,dt) {
	this.author = author;
	this.text = text;
	this.dt = dt;
};
var Post2 = function(text,comments) {
	this.text = text;
	this.comments = comments;
};
var Tmp = function() { };
Tmp.main = function() {
	console.log("Tmp.hx:72:","hello");
	var j = "{\n            \"text\": \"This is my first post\",\n            \"comments\": [{\n                \"author\": \"yokotoka\",\n                \"text\": \"Hello, world!\",\n                \"dt\": 11122\n            }]\n        }";
	var x = JSON.parse(j);
	console.log("Tmp.hx:85:",JSON.stringify(x));
};
Tmp.main();
})();
